lu-zero/cargo-c

- src/main.rs
Useful for odd distributions like Homebrew. In my case, `/usr/local/lib/pkgconfig` was the path.
A default of `/usr/local/lib/pkg-config` was inferred by cargo-c instead.
For consistency with autotools[1] the option is named `--with-pkgconfigdir`.
[1] https://www.mankier.com/7/pkg.m4#Autoconf_Macros-Pkg_installdir(Directory)
> Add --with-pkgconfigdir option

- README.md
I was wanting to use this project for the [gcode](https://crates.io/crates/gcode) crate, but it took a lot longer to track down the required steps than it should have.
This PR links to the original blog post and also copies the TL;DR into the README's *Usage* section.
> Provide the steps for adding `cargo-c` to your crate

- src/main.rs
c.f. #27 
The `.into()` didn't seem to work due to E0282, I didn't investigate too hard on how to fix that as it's already a bit late.
> cli: pass --jobs to cargo

- README.md
In commit c64eebd travis was removed, therefore the badge gives build error.
If you want a preview of how the new badge looks like go to my [README](https://github.com/MarcoIeni/cargo-c/blob/master/README.md)
> README: change travis badge with github actions one

- src/cbuild.rs
Not sure it's the right way to do that but should work too :)
Fix #62
> cbuild: respect --version when called as subcommand

- src/build.rs
- src/cli.rs
Get dlltool command from environment variable DLLTOOL or command line argument --dlltool. If not specified default to "dlltool".
Fixes #87
> Add dlltool argument

- src/build.rs
> Do not attempt to build impllib if building only static libraries

- README.md
- src/build.rs
Fixes https://github.com/lu-zero/cargo-c/issues/99
----
This is on top of https://github.com/lu-zero/cargo-c/pull/103
> Add optional min_version metadata to specify the minimum required cargo-c version

- .github/workflows/deploy.yml
- Add missing cargo-capi on linux/macos binary archive
- Remove target/release path on windows binary archive, to use the same file structure than other OSes.
> Fix CI binaries

- .github/workflows/deploy.yml
This prevents the release builds to depend on just the right homebrew installed version of OpenSSL on the system running the binaries.
> CI: Use vendored OpenSSL for macOS release builds

- src/build.rs
I am getting the following error:
```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1'
```
Looking at the code, it seems that if `targets.len()` is 1, then the first element should be `targets[0]` and not `targets[1]`.
> Fix 'index out of bounds' in build.rs

- .github/workflows/example-project.yml
- .gitignore
- example-project/Cargo.toml
- example-project/README.md
- example-project/cbindgen.toml
- example-project/src/capi.rs
- example-project/src/lib.rs
- example-project/usage-from-c/Makefile
- example-project/usage-from-c/run_tests.c
This is an extension of #113.
I've re-based this PR in order to take advantage of #116 (`Box<T>` gets converted to `*T`).
I've also extended the Rust example code a bit, using an opaque pointer in the C API. I think this is a typical use case, isn't it?
I've also added a test program and a corresponding `Makefile`. I also added a `README.md`.
I think it is good to test the actual linking and usage of the generated library in CI, which is now done for Linux and macOS.
I have no idea how such a thing is typically done in Windows, but I guess this can be added later by somebody else.
I guess an actual C unit test framework could be used to test this, but for now I chose the simpler option of a small hand-written test program.
For now, only a simple `Makefile` is shown as an example for a …
> Add minimal example project (including CI) - take 2

- README.md
- src/build.rs
- src/pkg_config_gen.rs
> add settings to define Require(.private) in pc file

- src/build.rs
- src/install.rs
- src/pkg_config_gen.rs
This can be used to use the generated library without installing it.
Will be required to integrate GStreamer Rust plugins with gst-build as it does not install the artifacts.
> generate -uninstalled .pc files

- src/pkg_config_gen.rs
Headers are generated in the build dir, not in the lib specific
subdirectory.
Fix #157
> uninstalled pc: fix include path

- src/build.rs
- src/target.rs
By default the host is passed.
It makes easier to pass additional rustflags without tripping over the
compilation of build-script and compiler plugins.
See #172 for an example.
> Always set the target triple

- .github/workflows/example-project.yml
This only seems to work with the GNU toolchain, which I guess makes sense.
I'm not an MSYS2 expert (in fact I've only ever used it on CI servers and I started very recently), so there might be a better way to do this.
It seems that `/usr/local/*` is not searched by default, I don't know why.
> CI: test example project in Windows/MSYS2

- README.md
- example-project/Cargo.toml
- src/bin/capi.rs
- src/bin/ctest.rs
- src/build.rs
- src/pkg_config_gen.rs
Fixes #172
Ideally I could try to add to `CompileOptions` a field and make so `TargetInfo::new` and `RustcTargetData::new` in cargo itself, but it might be too invasive for what seems to be needed only by us.
@sdroege Could you please test it and tell me if is working for you?
> Add a simple way to set the RUSTFLAGS from Cargo.toml

- src/install.rs
Should fix an error I encountered cross compiling rav1e.
```
Finished release [optimized + debuginfo] target(s) in 35.48s
Building pkg-config files
Building header file using cbindgen
thread 'main' panicked at 'not implemented: The target ios- is not supported yet', /Users/diatrus/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-c-0.8.1+cargo-0.53/src/install.rs:94:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
gmake[1]: *** [rav1e.mk:18: rav1e] Error 101
gmake: *** [Makefile:935: rebuild-rav1e] Error 2
```
> Support iOS in install.rs

- src/build.rs
The hasher is storing the hash as a u64 while toml is parsing it as a i64.
Toml does not support u64, making the parser failing because of the
overflow and so always forcing a rebuild.
Fix it by storing the hash as a string instead.
Fix #195
> build: fix u64 overflow when caching the hash

- coverage.sh
- example-project/Cargo.toml
- example-project/build.rs
- src/bin/capi.rs
- src/bin/cbuild.rs
- src/bin/cinstall.rs
- src/bin/ctest.rs
- src/build.rs
- src/cli.rs
This fixes crates using `cargo metadata` in build.rs due to how `cargo_exe()` is working.
> Make the applets able to forward calls to other applets

- .github/workflows/example-project.yml
- README.md
- example-project/Cargo.toml
- example-project/usage-from-c/Makefile
- example-project/usage-from-c/run_tests.c
- src/build.rs
- src/install.rs
- src/pkg_config_gen.rs
It should manage to tackle the remaining peculiarities mentioned in https://github.com/lu-zero/cargo-c/issues/204.
The additional install support being worked on will make possible to install multiple headers.
> Include path options

- Cargo.toml
- example-project/Cargo.toml
- example-project/build.rs
- src/build.rs
- src/build_targets.rs
- src/install.rs
- src/pkg_config_gen.rs
> Support custom pre-generated and generated include

- src/build.rs
- src/build_targets.rs
- src/cli.rs
- src/install.rs
- src/pkg_config_gen.rs
> Add datadir support

- .github/workflows/example-project.yml
I recently found out that there is a Rust package for MSYS2 (https://packages.msys2.org/base/mingw-w64-rust), and there is even a package for `cargo-c` (https://packages.msys2.org/base/mingw-w64-cargo-c)!
I tried to use the Rust package on CI, but still compile the latest version of `cargo-c` on the fly.
Sadly, there are a few problems ...
Currently, there is a build error during `cargo cinstall`, any ideas how to fix this?
After that, there might still be a problem with the library not being installed into the default location normally used for MSYS2, but for now that's blocked by the compilation error.
~There seems to be another error in the Windows build (the one without MSYS2), which should also be solved, but it isn't really related to this PR.~
> CI: use MSYS2 cargo package for example project

- src/build_targets.rs
- src/install.rs
- src/target.rs
For now I've used this to build cargo-c version 0.9.8 (later version contains an error when using latest libgit2-sys), see: https://github.com/haikuports/haikuports/pull/5534
Also have been able to build rav1e 0.5.1 with this.
> Add support for Haiku Operating System

- src/target.rs
the musl platform also supports shared objects having an SONAME, and
this function is called only when making a 'shared object', so this
should always be added
fixes https://github.com/lu-zero/cargo-c/commit/04a92bc497698cc822bc969307744eb929cc1eab where this was removed
even when generating a dynamic library forcefully by setting library
type to cdylib
fixes https://github.com/lu-zero/cargo-c/issues/267
> Add sonames on musl

- src/install.rs
We assume they are plugins as meson does, as discussed in #271.
Fixes #271
> Install the windows DLL in the libdir if it is custom

- src/build_targets.rs
- src/install.rs
- src/target.rs
With this change in place I was able to build the `rav1e` C-API on [OmniOS](https://omnios.org/) (an illumos based OS).
> add support for illumos

- .github/workflows/deploy.yml
- Cargo.toml
I'm using cross to build a binary for the aarch64-unknown-linux-musl target, which avoids glibc ABI compatibility issues with the gcc from crossbuild-essential-arm64 and so can run on more platforms. I've also added i686 linux musl binaries to the deploy workflow. The binary created by aarch64-unknown-linux-gnu only runs on the most recent distributions because of the version of glibc it is linked against. Executing the binaries from the v0.9.14-deploy release on debian buster (and el7) fails with the error:
```
cargo-cinstall: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by cargo-cinstall)
cargo-cinstall: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by cargo-cinstall)
```
I've created a test release on my fork …
> ci(deploy): Use musl abi for aarch64 linux binary, add i686 linux

- src/target.rs
And the equivalent change for macOS/iOS.
Fixes https://github.com/lu-zero/cargo-c/issues/295
> Don't include version in soname ELF header if versioning is disabled

- src/target.rs
This is needed to be able to add multiple RPATH entries, and also to change the install_name itself. This is enabled by default in Meson.
> macos: Allow larger install_name entries

- README.md
- src/build.rs
- src/install.rs
- src/pkg_config_gen.rs
It is used to disable the generation of import_libraries when unnecessary in platforms that need it to link libraries (e.g. Windows).
@sdroege could you please check if it would work for gst?
> Add a library.import_library configuration option

- src/build_targets.rs
- src/install.rs
- src/target.rs
Tested using commit https://github.com/kleisauke/wasm-vips/commit/4e335c7febc2019963c8678a94d9650f7635d158.
> Add support for Emscripten

- README.md
Sometimes used via [mpv](https://github.com/mpv-player/mpv/commit/41ad51bda281) -> libplacebo -> libdovi [![Packaging status](https://repology.org/badge/tiny-repos/libdovi.svg)](https://repology.org/project/libdovi/versions)
> README: add libdovi to Users section

- .github/workflows/rust.yml
- Cargo.toml
And update cargo to 0.72.2 and pin strip-ansi-escapes since 0.1.2 is broken.
Fixes #332.
> Prepare for release

- src/target.rs
Related to #345
With this patch applied Arch Linux generates this metadata (emphasis on `Provides`):
```
Name            : librustls
Version         : 0.11.0-1
Description     : Use rustls from languages other than Rust
Architecture    : x86_64
URL             : https://github.com/rustls/rustls-ffi
Licenses        : Apache-2.0  MIT
Groups          : None
Provides        : librustls.so=0.11-64
```
> Fix sover detection for 0-based versioning

- README.md
- src/build.rs
- src/install.rs
- src/lib.rs
- src/pkg_config_gen.rs
- src/target.rs
Related to #345 (this patch is based on my comment there) and rustls/rustls-ffi/pull/274.
This adds a setting to disable automatic semver SONAMEs and to pick an arbitrary number of components from the version string for the SONAME.
This feature allows two additional use-cases for library developers to pick from:
For a C-style breaking-change counter use a config like this:
```toml
[package.metadata.capi.library]
name = "imagequant"
version = "0.0.0"
version_suffix_components = 1
```
Increase the major version for every time the ABI is broken:
```toml
[package.metadata.capi.library]
name = "imagequant"
version = "1.0.0"
version_suffix_components = 1
```
This pattern is already supported, but one has to start at `.so.1` because it's currently not possible to configure `.so.0`.
Doing this …
> Add version_suffix_components setting

- src/build_targets.rs
- src/install.rs
- src/target.rs
Rust supports tvOS on [Tier 3](https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-3). Has tested build [libdovi](https://github.com/quietvoid/dovi_tool/tree/main/dolby_vision).
> Add tvOS support

- README.md
cargo-c has been used since version 0.12.1 :-)
Thanks again!
> docs: add rustls-ffi to README users list

- .github/workflows/example-project.yml
- Cargo.toml
- src/build.rs
- src/build_targets.rs
- src/cli.rs
- src/install.rs
- src/target.rs
Hi @lu-zero,
This PR tries to implement the necessary bits to support the following Meson conventions:
- autodetection of `libdir` under Debian distros
- installation of PDB symbols under MSVC
- calling static libraries `libfoo.a` and import libraries `foo.lib` under MSVC
The second item is done in a way that allows adding support for other OSes (as what's needed is passing `-C split-debuginfo=packed`, and this is the default on macOS).
Setting it as draft before testing; will do so later next week, but I wanted to get some early feedback first.
cc @nirbheek 
Fixes #279 
Fixes #280 
Fixes #317
> Implement Meson parity

- src/install.rs
Hi,
This PR is to address an issue found in https://github.com/AOMediaCodec/libavif/pull/2228#discussion_r1653512613 . PDB symbols being missing (due to the `release` profile or `strip` being set) should not cause an install failure.
Let me know what you think.
> Allow debug symbols install to be skipped if they are not present

- src/build_targets.rs
- src/install.rs
- src/target.rs
Rust has provided support for visionOS on  [Tier 3](https://doc.rust-lang.org/nightly/rustc/platform-support/apple-visionos.html) and published on v1.79.0. Has tested build [libdovi](https://github.com/quietvoid/dovi_tool/tree/main/dolby_vision).
> Add visionOS support

- Cargo.toml
Recently released: https://github.com/mozilla/cbindgen/releases/tag/v0.27.0
It allows support for using C-string literals, coming from `syn` update.
I'm not sure if anything else needs checking, it builds and passes the tests.
> Update cbindgen dependency to version 0.27.0

- src/build.rs
A terribly tiny PR to follow up on [#394](https://github.com/lu-zero/cargo-c/issues/394)
This works for my no-std package, and the coverage script still passes. If there's anything else needed just let me know!
> Handle unwrap when link line is empty, i.e. nostd crates.

- Cargo.toml
- src/build.rs
Gets rid of two more nasty `Command` invocations. This'll need a rebase once https://github.com/lu-zero/cargo-c/pull/402 is merged, but we can handle any review comments already. 
This time the logic is effectively untested by me, and would really benefit from the CI improvements suggested in the other PR.
> Generate import libraries without `Command`

- .github/workflows/example-project.yml
- example-project/usage-from-c/meson.build
- src/build.rs
Hi @lu-zero ,
In https://github.com/lu-zero/cargo-c/pull/402#issuecomment-2343233329 I mentioned that the pkg-config generator needed a bit more work for it to work with MSVC.
This PR converts the output of `native-static-libs` to match the expected format of pkg-config (`-lfoo`, instead of `foo.lib`). I've also added the needed bit for this to be tested in CI.
Let me know what you think.
> Fix pkg-config library output for MSVC and enable Windows CI

- Cargo.toml
also sets the version to the version used by `implib`, so `object` does not get built twice
> reduce the number of feature flags enabled for `object`

- src/build.rs
- src/build_targets.rs
- src/pkg_config_gen.rs
why use vectors of strings when two booleans will do.
> add `LibraryTypes`

- src/build.rs
We were always using the first package link line, leading to broken pkg-config files.
For example in
https://gitlab.freedesktop.org/thiblahute/gst-plugins-rs/-/jobs/64909911, we can see that static linking using that `.pc` file doesn't work as it is not linking to `stdc++` in that specific case.
> pkg-config: Use the right link-line when generating pkg-config files

- README.md
> Clarify that the `TL;DR` section is not a list of requirements

- src/build.rs
- src/build_targets.rs
- src/install.rs
This PR fixes two issues when using `--meson-paths`.
- Ensure import libraries under MinGW are named `libfoo.dll.a` (44e96dcd46a6e2385e328d1bc914707b4c04a8c9).
```diff
@@ -4,5 +4,5 @@
Copying /tmp/rav1e/x86_64-pc-windows-gnullvm/release/rav1e.h to /usr/x86_64-w64-mingw32/include/rav1e/rav1e.h
Installing shared library
Copying /tmp/rav1e/x86_64-pc-windows-gnullvm/release/rav1e.dll to /usr/x86_64-w64-mingw32/bin/librav1e.dll
-     Copying /tmp/rav1e/x86_64-pc-windows-gnullvm/release/rav1e.dll.a to /usr/x86_64-w64-mingw32/lib/rav1e.lib
+     Copying /tmp/rav1e/x86_64-pc-windows-gnullvm/release/librav1e.dll.a to /usr/x86_64-w64-mingw32/lib/librav1e.dll.a
Copying /tmp/rav1e/x86_64-pc-windows-gnullvm/release/rav1e.def to /usr/x86_64-w64-mingw32/lib/rav1e.def
```
- Shared libraries under MSVC …
> Fix Meson naming convention

- Cargo.toml
- src/build.rs
Override `import_name` after parsing the `.def` file, as `-Wl,--output-def,` in LLVM and Binutils does not include a library name in the generated `.def` file.
https://github.com/lu-zero/cargo-c/blob/c37aec4d53076c3198c38e3d2cf187e35e199d95/src/target.rs#L112-L118
https://github.com/llvm/llvm-project/blob/llvmorg-19.1.6/lld/COFF/MinGW.cpp#L173-L192
https://github.com/bminor/binutils-gdb/blob/binutils-2_43_1/binutils/dlltool.c#L1813-L1872
Also bump `implib` while we are here, to ensure the import library works when targeting `i686-pc-windows-gnu{,llvm}`.
> Fix import lib generation under MinGW

- src/build.rs
> Hash the cargo metadata

- src/build.rs
Building cdylibs can only work on musl when the CRT is not statically linked: `RUSTFLAGS="-C target-feature=-crt-static"` however we have no way to detect that case.
It's better to always allow it, and let the user find the "troubleshooting" section of cargo-c when they encounter an error.
In nightly rust, we can detect this case and we can add it once it's in stable.
Fixes https://github.com/lu-zero/cargo-c/issues/458
> Always allow building cdylibs on musl

- src/pkg_config_gen.rs
Hi @lu-zero ,
This fixes using the GStreamer plugins .pc files with e.g. CMake, which interprets backslashes as an escape code and strips them automatically.
This is an upstream fix for the following GStreamer MR: https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/1895
cc @nirbheek
> Fix non-POSIX paths in Libdir under Windows

- src/build.rs
Hi @lu-zero ,
This MR fixes a mishap I found when testing the static version of GStreamer's Rust plugins: the code of `static_libraries` was monching `-framework` flags, which are unfortunately compound (followed by spaces instead of the `-Wl,-framework` form).
Removing the `uniq()` is sufficient, for a more optimized version I'll have to implement the deduplication in #470 .
> Fix static_libraries swallowing sequence of -framework flags
