lu-zero/cargo-c

src/main.rs

Windows (GNU ABI) Fixes

---

src/main.rs

We have to use dlltool to do this, based on the def, since using -Wl,--out-implib always codes the linked DLL name in the resulting implib, which we rename at install time.
Fixes https://github.com/lu-zero/cargo-c/issues/23.
CC: @jamrial

Windows: Use dlltool to generate the import lib

---

.travis.yml

Travis: Add basic testing and coverage

---

.github/workflows/rust.yml

Example run: https://github.com/1480c1/cargo-c/commit/1bca113fd2013beeb581030601842f952db7e287/checks

actions: Add rust.yml

---

.github/workflows/deploy.yml

This PR is a follow up of #60 and closes #44 
Thanks in advance for your review! :)

Deploy cargo-c automatically

---

.github/workflows/deploy.yml

This PR fixes #70
Thanks in advance for your review! :)

Deploy cargo-c binaries

---

.github/workflows/deploy.yml

This PR allows to deploy `Linux` binaries without external dependencies.
Thanks in advance for your review! :)

Deploy on linux using musl

---

.github/workflows/deploy.yml

Simplify the code stripping windows binaries directly on `Windows`
Thanks in advance for your review! :)

Strip windows binaries directly on Windows

---

src/cinstall.rs

it should make easier debug and inspect.

Add some context to fs::copy

---

src/cinstall.rs

It currently uses is_absolute() to strip one leading component which doesn't
work for paths like "C:/foo", "C:foo" and "/foo" which are either not absolute
or have multiple components that need to be stripped.
The goal is to join two paths and removing any components from the second
one that would result in the first one being replaced/changed.
push()/join() alters the first path if it starts with a RootDir, Prefix, or both, so
we push everything from the second path except for those.
Fixes #89

append_to_destdir: handle Windows paths properly

---

src/bin/capi.rs
src/bin/cbuild.rs
src/bin/cinstall.rs
src/cli.rs

Improve cargo-c cli documentation

---

.github/workflows/rust.yml

- Reduce the CI time a bit
- Coverage cross-platform code only

Run grcov on ubuntu-nightly only

---

README.md
src/bin/capi.rs
src/bin/cinstall.rs
src/build.rs
src/build_targets.rs
src/install.rs
src/pkg_config_gen.rs
src/target.rs

Fixes https://github.com/lu-zero/cargo-c/issues/12

Add support for overriding pkg-config name/description/version

---

src/build_targets.rs
src/target.rs

I only tested it with static builds.

Add iOS support

---

src/install.rs

The pkgconfig generation needs to know the include path w/out the
now-optional subdirectory.
Fixes: #121

Save the include subdir to a specific field

---

.github/workflows/example-project.yml
example-project/Cargo.toml
example-project/usage-from-c/run_tests.c

example project: remove header sub-directory

---

src/build.rs
src/target.rs

Don't build shared libraries for musl targets

---

Cargo.toml
example-project/Cargo.toml
example-project/src/lib.rs
example-project/tests/capi.rs
src/bin/capi.rs
src/bin/cinstall.rs
src/bin/ctest.rs
src/build.rs
src/cli.rs

Its usage should be documented a bit more.

Cargo ctest

---

.github/workflows/example-project.yml

This is marked as "draft" because it doesn't seem to run successfully on Windows.

CI: Add "cargo ctest"

---

README.md
src/build.rs
src/install.rs
src/pkg_config_gen.rs

See #135 for the context and API discussion.

Add options needed to build plugins

---

src/build.rs
src/build_targets.rs
src/install.rs

don't rebuild pc file if cache has not been invalidated

---

src/pkg_config_gen.rs

Looks like some copy/paste issue.

fix PkgConfig setters

---

.github/workflows/example-project.yml
Cargo.toml
src/build.rs

Use CC to find dumpbin

---

src/build.rs
src/build_targets.rs

Patch the target name to the custom name if provided

---

.github/workflows/rust.yml
coverage.sh

It should make simpler to run it locally.

Move the code coverage in a stand-alone script

---

src/build.rs
src/pkg_config_gen.rs

Use a dedicated directory for the uninstalled header files

---

src/build.rs
src/install.rs

We get better errors for free and simpler code

Use cargo_util for the fs operations

---

.github/workflows/example-project.yml
Cargo.toml
example-project/usage-from-c/Makefile
example-workspace/Cargo.toml
example-workspace/api-a/Cargo.toml
example-workspace/api-a/src/lib.rs
example-workspace/api-b/Cargo.toml
example-workspace/api-b/src/lib.rs
src/build.rs
src/cli.rs

This will address #63, @gdesmott if you have some timeslices to test would be great.
I'd fold a release with everything during the next week.

Cargo 0.56 workspace support

---

README.md
src/build.rs
src/cli.rs

@naokiri let me know if it still works for you (and sorry again for belatedly noticing github closed your PR)

Datadir support improvements

---

src/install.rs
src/target.rs

Also special-case major == 0.
Fixes #249.

Do not use the patch version in macOS -install_name

---

README.md

Add udbserver to users

---

.github/workflows/rust.yml

Remove actions-rs/cargo

---

Cargo.toml
src/bin/capi.rs
src/bin/cbuild.rs
src/bin/cinstall.rs
src/bin/ctest.rs
src/build.rs
src/cli.rs
src/config.rs
src/install.rs
src/pkg_config_gen.rs

Notes:
- the help is fairly different, we might disable the colors while we wait for https://github.com/clap-rs/clap/issues/3234 since the current default is a tad too red for my taste.
- The changes are many I need help from the usual suspects to make sure I do not break anything (hi @slomo and @nirbheek)

Update to cargo-0.67 and clap-4

---

README.md
src/bin/capi.rs
src/cli.rs

Fixes https://github.com/lu-zero/cargo-c/issues/302

cli: drop bogus arguments after cargo update

---

README.md

See also https://github.com/freebsd/freebsd-ports/commit/4cd440845e24

README: add ebur128 to Users section

---

README.md

Describe how to handle cdylib issues with musl systems.
Resolves https://github.com/lu-zero/cargo-c/issues/180.

README: add Troubleshooting section

---

src/cli.rs
src/install.rs

Match the beaviour of meson regarding relative paths in the install directories

---

Cargo.toml
src/bin/ctest.rs
src/build.rs

And cleanup redundant imports.

Bump cargo version

---

Cargo.toml
src/build.rs
src/pkg_config_gen.rs

Do not install the versioned links and lib on Android

---

README.md

Add a note to warn about the behaviour change on debian-like systems

---

.github/workflows/example-project.yml
src/build_targets.rs

Fix the generated header fingerprinting logic

---

.github/workflows/example-project.yml

The workaround over ubuntu distributing a strange pkg-config requires further fixes...

Unbreak the CI

---

src/pkg_config_gen.rs

my knowledge of windows paths is limited, and I used wine to develop these tests so that is a slightly different environment, but at least this shows that the basics work.

path canonicalize windows tests

---

Cargo.toml

Bump rust version

---

src/build_targets.rs
src/install.rs
src/target.rs

This a set of patches by @ajacoutot, tested with a work-in-progress update for librsvg

Add initial support for OpenBSD

---

.github/dependabot.yml

- automate github-actions dependency updates

chore(dependabot): automate github-actions dependency updates

---

Cargo.toml

Bump implib

---

src/build.rs

Fix file regeneration logic
